from init import repo_file, repo_find, repo_dir
from hash import object_read, object_write
import os
import re

from utils import silent
import logging
logger = logging.getLogger(__name__)
from models.commit import GitTag

REF_PREFIX = 'ref: '
def ref_resolve(repo, ref):
    path = repo_file(repo, ref)

    # Sometimes, an indirect reference may be broken.  This is normal
    # in one specific case: we're looking for HEAD on a new repository
    # with no commits.  In that case, .git/HEAD points to "ref:
    # refs/heads/main", but .git/refs/heads/main doesn't exist yet
    # (since there's no commit for it to refer to).

    if not os.path.isfile(path):
        return None

    with open(path) as f:
        data = f.read().rstrip('\n')

    if data.startswith(REF_PREFIX):
        return ref_resolve(repo, data.lstrip(REF_PREFIX))
    else:
        return data

def ref_list(repo, path = None):
    if path is None:
        path = repo_dir(repo, 'refs')

    ret = {}
    for item in sorted(os.listdir(path)):
        item_path  = os.path.join(path, item)
        if os.path.isdir(item_path):
            ret[item] = ref_list(repo, item_path)
        else:
            ret[item] = ref_resolve(repo, item_path)

    return ret

def show_ref(repo , refs, with_hash = True, prefix = ''):
    if prefix != '':
        prefix += '/'

    for item in refs:
        val = refs[item]

        if type(val) != str:

            logger.debug(f"k : v  = {item}:{val}")
            logger.debug("type of item is: %s",type(val))
            show_ref(repo, val, with_hash, prefix+item)

        elif with_hash:
            print(f"{val} {prefix}{item}")
        else:
            print(f"{prefix}{item}")

def cmd_show_ref(args):
    repo = repo_find()
    refs = ref_list(repo)
    show_ref(repo, refs, prefix = 'refs')


def ref_create(repo, ref, hash):
    with open(repo_file(repo, 'refs/'+ref), 'w') as f:
        f.write(hash + '\n')



def tag_create(repo, tag_name, ref, create_tag_object = False):
    hash = object_find(repo, ref)
    
    if create_tag_object:
        tag = GitTag()
        data = {}
        data[b'object'] = hash.encode()
        print("hash is of type ", type(hash))
        print("object is of type ", type(data[b'object']))
        data[b'type'] = b'commit'
        data[b'tag'] = tag_name.encode()
        data[b'tagger'] = b'Asterisk07 <ferbandphineas100@gmail.com>'
        data[None] = b"A tag generated by wyag, which won't let you customize the message!\n"

        for k in data:
            data[k] += b'\n'
        tag.data = data
        tag_hash = object_write(tag, repo)

    else:
        tag_hash = hash
    ref_create(repo, 'tags/' + tag_name, tag_hash )
    # print("Created tag")

def cmd_tag(args):
    repo = repo_find()
    if args.name:
        tag_create(repo, args.name, args.object, args.create_tag_object)
        # raise NotImplementedError
    else:
        refs = ref_list(repo)
        show_ref(ref_list, refs['tags'], with_hash = False)

HASH_REGEX = re.compile('^[0-9A-Fa-f]{4,40}$')
def object_resolve(repo, name):
    """Resolve name to an object hash in repo.

    This function is aware of:

    - the HEAD literal
    - short and long hashes
    - tags
    - branches
    - remote branches"""


    if not name.strip():
        return None


    if name == 'HEAD':
        return [ref_resolve(repo, name)]

    candidates = []


    if HASH_REGEX.match(name):
        logger.debug(f'name is hash')

        hash = name.lower()
        prefix = hash[:2]
        dir_path = repo_dir(repo,"objects", prefix, mkdir = False)

        if dir_path:
            logger.debug(f'dir match hash')

            rest_hash = hash[2:]
            for f in os.listdir(dir_path):

                if f.startswith(rest_hash):
                    logger.debug(f'obj match hash')

                    candidates.append(prefix + f)
    else:
        logger.debug(f'name {name} not match hash {HASH_REGEX}')


    for subfolder in ('tags','heads','remotes'):
        hash = ref_resolve(repo, f'refs/{subfolder}/{name}')
        if hash:
            candidates.append(hash)
    return candidates

def object_find(repo, name, fmt=None, follow=True) -> str:
    hash = object_resolve(repo, name)
    # raise Inde
    logger.debug(f'resolved obj, got hash : {hash} for name : {name}')

    if not hash:
        raise Exception(f"No such reference {name}.")
    elif len(hash) > 1:
        raise Exception(f"Ambiguous reference {name}: Candidates are:\n - {'\n - '.join(hash)}.")
    else:
        hash = hash[0]

    if fmt is None:
        return hash
    
    while True:
        obj = object_read(repo, hash)
        if obj.fmt == fmt:
            assert(hash is not None)
            return hash
        
        if not follow:
            assert(None is not None)

            return None
        
        if obj.fmt == b'tag':
            hash = obj.data[b'object'].decode('ascii')
        elif obj.fmt == b'commit':
            hash = obj.data[b'tree'][-1].decode('ascii')
        else:
            logger.debug(f'Invalid fmt {obj.fmt}, returning None hash instead of {hash} for name : {name}')

            # assert(None is not None)

            return None


    # if len(sha) > 1:
    return name